channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - aws-c-auth=0.7.3=h0127223_1
  - aws-c-cal=0.6.1=hfb91821_1
  - aws-c-common=0.9.0=hcfcfb64_0
  - aws-c-compression=0.2.17=h04c9df6_2
  - aws-c-event-stream=0.3.1=h495bb32_4
  - aws-c-http=0.7.11=hf013885_4
  - aws-c-io=0.13.32=he824701_1
  - aws-c-mqtt=0.9.5=h64f41f2_0
  - aws-c-s3=0.3.14=hb8b96c7_1
  - aws-c-sdkutils=0.1.12=h04c9df6_1
  - aws-checksums=0.1.17=h04c9df6_1
  - aws-crt-cpp=0.23.0=h752f25a_2
  - aws-sdk-cpp=1.10.57=h22002f8_20
  - boost=1.78.0=py311h12feb9d_4
  - boost-cpp=1.78.0=h9f4b32c_1
  - brotli=1.0.9=hcfcfb64_8
  - brotli-bin=1.0.9=hcfcfb64_8
  - brotlipy=0.7.0=py311ha68e1ae_1005
  - bzip2=1.0.8=h8ffe710_4
  - c-ares=1.19.1=hcfcfb64_0
  - ca-certificates=2023.7.22=h56e8100_0
  - cairo=1.16.0=hd694305_1014
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py311h7d9ee11_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - contourpy=1.0.7=py311h005e61a_0
  - cryptography=39.0.2=py311h28e9c30_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - expat=2.5.0=h1537add_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.0=py311ha68e1ae_0
  - freetype=2.12.1=h546665d_1
  - gettext=0.21.1=h5728263_0
  - greenlet=2.0.2=py311h12c1d0e_0
  - icu=70.1=h0e60522_0
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2023.0.0=h57928b3_25922
  - joblib=1.2.0=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py311h005e61a_1
  - krb5=1.21.2=heb0366b_0
  - lcms2=2.15=h3e3b177_1
  - lerc=4.0.0=h63175ca_0
  - libabseil=20230125.3=cxx17_h63175ca_0
  - libarrow=13.0.0=h10ad630_0_cpu
  - libblas=3.9.0=16_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_8
  - libbrotlidec=1.0.9=hcfcfb64_8
  - libbrotlienc=1.0.9=hcfcfb64_8
  - libcblas=3.9.0=16_win64_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.2.1=hd5e4a3a_0
  - libdeflate=1.17=hcfcfb64_0
  - libevent=2.1.12=h3671451_1
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.74.1=he8f3873_1
  - libgoogle-cloud=2.12.0=hbc1b25b_1
  - libgrpc=1.56.2=hea2d5f7_1
  - libhwloc=2.9.0=h51c2c0f_0
  - libiconv=1.17=h8ffe710_0
  - libjpeg-turbo=2.1.5.1=hcfcfb64_0
  - liblapack=3.9.0=16_win64_mkl
  - libpng=1.6.39=h19919ed_0
  - libprotobuf=4.23.3=h1975477_0
  - libsqlite=3.40.0=hcfcfb64_0
  - libssh2=1.11.0=h7dfc565_0
  - libthrift=0.18.1=h06f6336_2
  - libtiff=4.5.0=hc3b8658_5
  - libutf8proc=2.8.0=h82a8f57_0
  - libwebp-base=1.3.0=hcfcfb64_0
  - libxcb=1.13=hcd874cb_1004
  - libxgboost=1.7.4=cpu_h20390bd_0
  - libxml2=2.10.3=hc3477c8_3
  - libzlib=1.2.13=hcfcfb64_4
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-base=3.7.1=py311h6e989c2_0
  - mkl=2022.1.0=h6a75c08_874
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - numpy=1.24.2=py311h0b4df5a_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openpyxl=3.1.2=py311ha68e1ae_0
  - openssl=3.1.2=hcfcfb64_0
  - orc=1.9.0=hf2b8f0d_1
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.3=py311hf63dbb6_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=h17e33f8_0
  - pillow=9.4.0=py311hc67b2de_2
  - pip=23.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - platformdirs=3.1.1=pyhd8ed1ab_0
  - pooch=1.7.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - py-xgboost=1.7.4=cpu_py311h3180b0a_0
  - pyarrow=13.0.0=py311h6a6099b_0_cpu
  - pycairo=1.23.0=py311h99894aa_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.11.0=hcf16a7b_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2022.7.1=pyhd8ed1ab_0
  - rdkit=2022.09.5=py311h5f60fae_0
  - re2=2023.03.02=hd4eee63_0
  - reportlab=3.6.12=py311hae2e3ae_2
  - requests=2.28.2=pyhd8ed1ab_0
  - scikit-learn=1.2.2=py311h6619ee7_0
  - scipy=1.10.1=py311h37ff6ca_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=67.6.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hfb803bf_0
  - sqlalchemy=2.0.6=py311ha68e1ae_0
  - statsmodels=0.13.5=py311h59ca53f_2
  - tbb=2021.8.0=h91493d7_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h8ffe710_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - vc=14.3=hb6edc58_10
  - vc14_runtime=14.34.31931=h5081d32_13
  - vs2015_runtime=14.34.31931=h4c5c07a_10
  - wheel=0.40.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - zlib=1.2.13=hcfcfb64_4
  - zstd=1.5.2=h12be248_6
  - pip:
    - asttokens==2.2.1
    - backcall==0.2.0
    - colorama==0.4.6
    - comm==0.1.2
    - debugpy==1.6.6
    - decorator==5.1.1
    - executing==1.2.0
    - ipykernel==6.21.3
    - ipython==8.11.0
    - jedi==0.18.2
    - jupyter-client==8.0.3
    - jupyter-core==5.2.0
    - matplotlib-inline==0.1.6
    - nest-asyncio==1.5.6
    - parso==0.8.3
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.38
    - psutil==5.9.4
    - pure-eval==0.2.2
    - pygments==2.14.0
    - pywin32==305
    - pyzmq==25.0.1
    - stack-data==0.6.2
    - tornado==6.2
    - traitlets==5.9.0
    - wcwidth==0.2.6